// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbnwmoitifuaxmvtycgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtibndtb2l0aWZ1YXhtdnR5Y2duIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTI3OTEsImV4cCI6MjA3MDIyODc5MX0.pSsSPQ3rATMRQP_YWs3-G1gqvkrvebPXAfxBsNRsVO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});